### ISSUE TITLE
Chapter02 - InputStreamSource is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by NoamB** [PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition#1]
https://github.com/PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition/blob/b190a5fd021f89dd2fddf81757aafb9c9a54ae56/Chapter02/part1/src/main/java/com/greglturnquist/learningspringboot/HomeController.java#L71

**Comment by gregturn** [comment]
It's InputStreamRrsource and it's not abstract. 

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/InputStreamResource.html

**Comment by NoamB** [comment]
Sorry, my mistake!
