### ISSUE TITLE
Chapter 01: List of empty json objects with Lombok

### ISSUE THREAD

**Issue by majorgilles** [PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition#2]
Hello, there seems to be an issue when mapping the Flux<Chapter> result to json when the entities are using Lombok: I get [{}, {},{}] as a response (even with the provided code in this repository).

If I remove the Data annotation from the Chapter entity, and generate plain old getters and setters, there is no issue in the json response, the id and name fields do appear.

**Comment by esmeetu** [comment]
Maybe you use IntelliJ.

Solution:
Preferences (Ctrl + Alt + S)
> Build, Execution, Deployment
>>Compiler
>>>Annotation Processors
>>>>Enable annotation processing

Make sure you have the Lombok plugin for IntelliJ installed!

Preferences -> Plugins
>Search for "Lombok Plugin"
>>Click Browse repositories...
>>>Choose Lombok Plugin
>>>>Install
>>>>>Restart IntelliJ

**Comment by gregturn** [comment]
A quick “tell” is to shutdown the IDE and build the code with gradle. If it works then and indeed it was IDEA.

**Comment by julekgwa** [comment]
Use gradle to build your project, ```./gradlew clean build ``` and to run the project do ```java -jar build/libs/name-of-project.jar```

**Comment by gaurav-packt** [comment]
Thanks for the update.
