### ISSUE TITLE
Chapter1 - Problem in init method of LoadDatabase

### ISSUE THREAD

**Issue by anita-87** [PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition#3]
I'm optaining this compilation error:

_Error:(20, 29) java: incompatible types: cannot infer type-variable(s) R,S
    (argument mismatch; bad return type in method reference
      S cannot be converted to org.reactivestreams.Publisher<? extends R>)_

In the method init of the LoadDatabase class:

```
@Bean
    CommandLineRunner init(ChapterRepository repository) {
        return args -> {
            Flux.just(
                    new Chapter("Quick Start with Java"),
                    new Chapter("Reactive Web with Spring Boot"),
                    new Chapter("...and more!"))
                    .flatMap(repository::save)
                    .subscribe(System.out::println);
        };
    }
```

The problem is in the line: `.flatMap(repository::save)`

Any idea why this happends?

**Comment by gregturn** [comment]
Have you checked out https://github.com/learning-spring-boot/learning-spring-boot-2nd-edition-code?

That repository (the source I wrote for the book) has been updated to use Spring Boot 2.0.0.RELEASE. Perhaps you could test out your issue against that version?

**Comment by anita-87** [comment]
I tested it with your code and it was working, I'm not really sure what I was doing wrong, but thank you for your answer.
