### ISSUE TITLE
 flux fluent by example in Korean translation

### ISSUE THREAD

**Issue by wiv33** [PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition#8]
It is the source content registered on page 73 of Korean translation.
The return has been changed, but I want you to tell me if it's a different version or a typo.

Flux.just("alpha", "bravo", "charlie")
            .map(String::toUpperCase)
            .flatMap(s -> Flux.fromArray(s.split("")))
            .groupBy(String::toString)
//    .sort((s1, s2) -> s1.key().compareTo(s2.key()));
//            .flatMap(group -> Mono.just((group.key()).zipWith(group.count()))

          
            Mono.just(): Mono<T>

            will return Mono<Void>
            Mono.just().and(): Mono<Void>
            .flatMap(group -> Mono.just(group.key()).and(group.count()))

            .map(keyAndCount -> keyAndCount.getT1() + " => " + keyAndCount.getT2())
            .subscribe(System.out::println);

**Comment by gregturn** [comment]
The book is based on Spring Boot 2.0. Are you using 2.3?

If so you may wish to investigate something a little more up to date. 

https://www.amazon.com/dp/B086722L4L/ref=mp_s_a_1_1?dchild=1&keywords=greg+l+turnquist&qid=1597762896&sprefix=greg+l+&sr=8-1

Ebook is currently on sale!
